web1.0/web1.0/Controllers/BanSachController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using web1._0.Common;
using web1._0.DAO;
using web1._0.Models;

namespace web1._0.Controllers
{
    public class BanSachController : BaseController
    {
        public static string img_edit = null;
        public static BaiDang bd_edit = new BaiDang();
        // GET: BanSach
        public ActionResult Index(int page = 1, int PageSize = 3)
        {

            UserLogin a = (UserLogin)Session[CommonConstrants.USER_SESSION];
            if (a != null)
            {
                var dao = new DAO.BaiDangDAO();
                int totalRecord = 0;
                var model = dao.getListBaiDang(a.ID,ref totalRecord, page, PageSize);
                ViewBag.total = totalRecord;
                ViewBag.Page = page;
                int maxPage = 3;
                int totalPage = 0;
                totalPage = (int)Math.Ceiling((double)(totalRecord / PageSize)) + 1;
                ViewBag.totalPage = totalPage;
                ViewBag.Maxpage = maxPage;
                ViewBag.First = 1;
                ViewBag.Last = totalPage;
                ViewBag.Next = page + 1;
                ViewBag.Prev = page - 1;
                return View(model);
            }

            return View();
        }

        public ActionResult Xoa(BaiDang bd)
        {

            var dao = new DAO.BaiDangDAO();
            int ID = dao.XoaDonHang(bd.ma);
            return View("Index", dao.getListBaiDang2(ID));
        }
        public ActionResult convert(BaiDang bd)
        {
            var dao = new DAO.BaiDangDAO();
            BaiDang bdsua = dao.SuaBaiDang(bd);
            return View("TrangSua",bd);
        }

        public ActionResult TrangSua(BaiDang bd)
        {
            //if (bd != null)
            //    bd_edit = bd;
            //if (img_edit != null)
            //{
            //    bd.hinhanh = img_edit;
            //}

            convert(bd);
            return View(bd);
        }

        public ActionResult create(BaiDang bd)
        {
            UserLogin a = (UserLogin)Session[CommonConstrants.USER_SESSION];
            //bd_create = bd;
            var BDsum = new BaiDangDAO();
            BaiDang bd_temp = new BaiDang();
            bd.mataikhoan = a.ID;
            bd_temp.ten = null;
            string TacGia = Request.Form["TacGia"];
            string NXB = Request.Form["NXB"];
            string tenTheLoai = Request.Form["TheLoai"];
            if (BDsum.insertBaiDang(bd))
            {
                Response.Write("<script type=\"text/javascript\">alert('Tạo Bài đăng thành công !!! ');</script>");
                return View("create", bd_temp);
            }
            else
            {
                // img_create = null;
                return View("create", bd_temp);
            }
        }

               [HttpPost]
        public ActionResult UploadH(BaiDang viewModel, HttpPostedFileBase file)
        {
            if (file != null)
            {
                string path = Path.Combine(Server.MapPath("~/Image"),
                                             Path.GetFileName(file.FileName));
                file.SaveAs(path);
                string s = "/Image/" + Path.GetFileName(file.FileName);
                viewModel.hinhanh = s;
            }
            UserLogin a = (UserLogin)Session[CommonConstrants.USER_SESSION];
            var BDsum = new BaiDangDAO();
            viewModel.mataikhoan = a.ID;
            string TacGia = Request.Form["TacGia"];
            string NXB = Request.Form["NXB"];
            string tenTheLoai = Request.Form["TheLoai"];
            if (TacGia != null)
            {
                TacGia tempTG = new TacGia();
                tempTG = BDsum.getTacGiabyTen(TacGia);
                if (tempTG != null)
                    viewModel.setTG(tempTG);
                else
                {
                    if (BDsum.insertTacGia(TacGia))
                    {
                        tempTG = BDsum.getTacGiabyTen(TacGia);
                        viewModel.setTG(tempTG);
                    }
                    else
                        Response.Write("<script type=\"text/javascript\">alert('Insert tác giả không thành công!!! ');</script>");
                }


            }
            if (NXB != null)
            {
                NhaXuatBan tempTG = new NhaXuatBan();
                tempTG = BDsum.getNXBbyTen(NXB);
                if (tempTG != null)
                    viewModel.NhaXuatBan = tempTG;
                else
                {
                    if (BDsum.insertNXB(NXB))
                    {
                        tempTG = BDsum.getNXBbyTen(NXB);
                        viewModel.NhaXuatBan = tempTG;
                    }
                    else
                        Response.Write("<script type=\"text/javascript\">alert('Insert NXB không thành công!!! ');</script>");
                }


            }
            if (tenTheLoai != null)
            {
                TheLoai tempTG = new TheLoai();
                tempTG = BDsum.getTheloaibyTen(tenTheLoai);
                if (tempTG != null)
                    viewModel.TheLoai = tempTG;
                else
                {
                    if (BDsum.insertTheLoai(tenTheLoai))
                    {
                        tempTG = BDsum.getTheloaibyTen(tenTheLoai);
                        viewModel.TheLoai = tempTG;
                    }
                    else
                        Response.Write("<script type=\"text/javascript\">alert('Insert TheLoai không thành công!!! ');</script>");
                }


            }
            if (BDsum.insertBaiDang(viewModel))
            {

                Response.Write("<script type=\"text/javascript\">alert('Tạo Bài đăng thành công !!! ');</script>");
       
                return View("Index", BDsum.getListBaiDang2(a.ID));
            }
            else
            {
                Response.Write("<script type=\"text/javascript\">alert('Tạo Bài đăng ko thành công !!! ');</script>");

                return View("create", viewModel);
            }
        }


        [HttpPost]
        public ActionResult UploadH2(BaiDang viewModel, HttpPostedFileBase file)
        {
            if (file != null)
            {
                string path = Path.Combine(Server.MapPath("~/Image"),
                                             Path.GetFileName(file.FileName));
                file.SaveAs(path);
                string s = "/Image/" + Path.GetFileName(file.FileName);
                viewModel.hinhanh = s;
            }
            UserLogin a = (UserLogin)Session[CommonConstrants.USER_SESSION];
            var BDsum = new BaiDangDAO();
            viewModel.mataikhoan = a.ID; 
            convert(viewModel);
            return View("TrangSua",viewModel);
            }
        }
    }

web1.0/web1.0/Controllers/MuaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web1._0.Models;
using web1._0.DAO;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace web1._0.Controllers
{
    public class MuaController : BaseController
    {
        SanSachCu db = new SanSachCu();
        public static DonHang donhang = null;
        // GET: Mua
        public ActionResult Index()
        {
            UserLogin user = (UserLogin)Session[Common.CommonConstrants.USER_SESSION];
            if (user != null)
            {
                int idbook = Int32.Parse(Request["ma"]);
                donhang = new Models.DonHang();
                donhang.Sach = db.Saches.SingleOrDefault(x => x.ma == idbook ? true : false);
                donhang.masach = donhang.Sach.ma;
                donhang.TaiKhoan = db.TaiKhoans.SingleOrDefault(x => x.ma == user.ID ? true : false);
                donhang.mataikhoan = donhang.TaiKhoan.ma;
                donhang.tinhtrang = false;
                donhang.ngaygiao = DateTime.Today.AddDays(2);
                return View(donhang);
            }



            return View();
        }
        public ActionResult dathang()
        {
            var DAO = new DonHangDAO();
            var dao1 = new SachDAO();
            DonHang newDH = new DonHang();
            newDH.masach = donhang.masach;
            newDH.mataikhoan = donhang.mataikhoan;
            newDH.ngaygiao = donhang.ngaygiao;
            newDH.tinhtrang = donhang.tinhtrang;
            if (donhang == null)
            {
                return View("Index");
            }
            DAO.Insert(newDH);

            dao1.SaledBook(donhang.masach);

            TaiKhoan tk = null;
            UserLogin user = (UserLogin)Session[Common.CommonConstrants.USER_SESSION];
            if (user != null)
            {
                tk = db.TaiKhoans.SingleOrDefault(x => x.ma == user.ID ? true : false);
            }

            return View("kiemtradonhang", getdonhang(tk));
        }
        public ActionResult kiemtradonhang()
        {
            TaiKhoan tk = null;
            UserLogin user = (UserLogin)Session[Common.CommonConstrants.USER_SESSION];
            if (user != null)
            {
                tk = db.TaiKhoans.SingleOrDefault(x => x.ma == user.ID ? true : false);
            }

            return View(getdonhang(tk));
        }

        public IEnumerable< Hoa_Don> getHoaDon(TaiKhoan tk,int madh)
        {
            
            Hoa_Don hd = null;
           
            UserLogin user = (UserLogin)Session[Common.CommonConstrants.USER_SESSION];
            if (user != null)
            {

                hd = new Models.Hoa_Don();
                DonHang dh = new DonHang();
                Sach book = new Sach();
                dh = db.DonHangs.SingleOrDefault(x => x.ma == madh ? true : false);
                book = dh.Sach;
                tk = db.TaiKhoans.SingleOrDefault(x => x.ma == user.ID ? true : false);
                hd.tensach = book.ten;
                hd.tentk = tk.hoten;
                hd.ngaygiao = DateTime.Today.AddDays(2);
                hd.gia = book.gia;
                hd.diachi = tk.diachi;

            }
            yield return hd;
        }
        public IEnumerable<DonHang> getdonhang(TaiKhoan tk)
        {
            return (from dh in db.DonHangs where dh.mataikhoan == tk.ma select dh);
        }
        
        public ActionResult donhang1()
        {
            return View(db.DonHangs.ToList());
        }
       
        public ActionResult exreport()
        {
           
            TaiKhoan tk = null;
            UserLogin user = (UserLogin)Session[Common.CommonConstrants.USER_SESSION];
            if (user != null)
            {
                tk = db.TaiKhoans.SingleOrDefault(x => x.ma == user.ID ? true : false);
            }
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Views/Mua/bill.rpt")));
            rd.SetDataSource(getHoaDon(tk, int.Parse((string)RouteData.Values["id"])));

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            try
            {
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "aplication/pdf", "Don_Hang1.pdf");
            }
            catch
            {
                throw;
            }

        }


        }
    }

web1.0/web1.0/Controllers/ShowBDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web1._0.Controllers
{
    public class ShowBDController : Controller
    {
        // GET: ShowBD
        public ActionResult Index(int page=1,int PageSize=3)
        {
            var dao = new DAO.BaiDangDAO();
            int totalRecord = 0;
          var model = dao.getListBd(ref totalRecord, page, PageSize);
            ViewBag.total = totalRecord;
            ViewBag.Page = page;
            int maxPage = 3;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling( (double)(totalRecord / PageSize))+1;
            ViewBag.totalPage = totalPage;
            ViewBag.Maxpage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }
    }
}

web1.0/web1.0/Views/Shared/TimKiem.cshtml
@model web1._0.Models.TheLoai_Gia
<div class="panel panel-info">

    <div class="panel-heading">Tìm Kiếm</div>
    <div class="panel-body">
        <fieldset style="border:thin;color:#999;">
            @using (Html.BeginForm("KQTimKiem", "Home", FormMethod.Get, new { @class = "navbar-form navbar-right", role = "search", id = "search-form" }))
            {
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Tìm kiếm sách" name="SearchTerm" value="@ViewBag.SearchTerm" id="search-box">
                </div>
                    <div class="form-group">
                        <a href="~/Views/Shared/_Template.cshtml"></a>
                        <button type="submit" class="btn btn-default hidden-xs"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
            }

                <div class="form-group">
                    <p>Tìm kiếm theo danh mục</p>
                </div>
                <div class="form-group">
                  <label for="sel1">Select list:</label>
                  <select class="form-control" id="sel1" name="selected">
                 <option>Tìm theo sách</option>
                 <option>Tìm theo bài đăng</option>

                 </select>
                </div>
                <br />
                <br />
                <form>
                    <tr>
                        <td>
                            <b>Tác Giả:</b>
                        </td>
                        <td>
                            @Html.DropDownList("Listtacgia", new SelectList(Model.lsttacgia))


                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Thể Loại:</b>
                        </td>
                        <td>
                            @Html.DropDownList("Listtheloai", new SelectList(Model.lsttheloai))
                        </td>
                    </tr>
          
                </form>

                   
</fieldset>


    </div>


</div>

web1.0/web1.0/Views/Shared/_BdInList.cshtml
@model web1._0.Models.BaiDang



<div class="BookinList">
    <div class="hinh">
        <div class="container_1">
            <img class="hinh" src="@Model.hinhanh" alt="Avarta">
            <div class="overlay">
                <div class="text" align="left">
                    @Model.gioithieu
                </div>
            </div>

        </div>
    </div>
    <div class="overlay">
        <p class="text">@Model.gioithieu</p>
    </div>
    <div class="Info">
        <h3>@Model.ten</h3>
        <br />
        <br />
        <table>
            <tr>
                <td><b>Tác giả:</b></td>
                <td>@Model.TacGia.tentacgia</td>
            </tr>
            <tr>
                <td><b>Gioi Thieu:</b></td>
                <td>@Model.gioithieu</td>
            </tr>
            <tr>
                <td><b>Nhà xuất bản:</b></td>
                <td>@Model.NhaXuatBan.tennhaxuatban</td>
            </tr>
            <tr>
                <td><b>Thể loại:</b></td>
                <td>@Model.TheLoai.tenloaisach</td>
            </tr>

            <tr>
                <td><b>Giá: </b></td>
                <td>@Model.gia đ</td>
            </tr>
            <tr>
                <td><b>Ngay Dang: </b></td>
                <td>@Model.ngaydang đ</td>
            </tr>
        </table>

    </div>


</div>

web1.0/web1.0/Views/Shared/_BookInList.cshtml
@model web1._0.Models.Sach



<div class="BookinList">
    <div class="hinh">
        <div class="container_1">
            <img class="hinh" src="@Model.hinhanh" alt="Avarta">
            <div class="overlay">
                <div class="text" align="left">
                    @Model.gioithieu
                </div>
            </div>

        </div>
    </div>
    <div class="overlay">
        <p class="text">@Model.gioithieu</p>
    </div> 
    <div class="Info">
        <h3>@Model.ten</h3>
        <br />
        <br />
        <table>
            <tr>
                <td><b>Tác giả:</b></td>
                <td>@Model.TacGia.tentacgia</td>
            </tr>
            <tr>
                <td><b>Nhà xuất bản:</b></td>
                <td>@Model.NhaXuatBan.tennhaxuatban</td>
            </tr>
            <tr>
                <td><b>Thể loại:</b></td>
                <td>@Model.TheLoai.tenloaisach</td>
            </tr>

            <tr>
                <td><b>Giá: </b></td>
                <td>@Model.gia đ</td>
            </tr>
            <tr>
                <td></td>
                @using (Html.BeginForm("Index", "Mua",new {@Model.ma}))
                {
                    <td><input class="btn-primary" value="Đặc mua" type="submit" onclick="location.href='@Url.Action("Index", "Mua")'"/></td>
                }
               
               
            </tr>
            @Model.ngaydang
        </table>

    </div>


</div>

web1.0/web1.0/Views/Shared/_Template.cshtml
@{
    ViewBag.Title = "_Template";
}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <!-- TemplateBeginEditable name="title" -->
    <title>SanSachCu.tk</title>
    <!-- TemplateEndEditable -->
    <!-- incluce Bootrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.mi    n.js"></script>

    <!-- incluce bootrap-->
    <!--	mobile-->
    <meta name="viewport" content="width=divice-width, inial-scale=1">
    <!--	mobile-->

    <link href="~/Assets/CSS/style.css" rel="stylesheet" type="text/css">
    <script src="~/Assets/js/testjs.js"></script>
    <link href="~/Assets/CSS/font-awesome.min.css" rel="stylesheet" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="~/Assets/js/lienhe.js"></script>
</head>
<body>
    <div class="container"> 
                    <!--{Html.RenderAction("CheckSession", "TaiKhoan");}-->
                    @Html.Action("CheckSession", "TaiKhoan") 
        <div class="row">
            <div class="col-4 justify-content-between"></div>
            <div class="col-4"><img src='~/Assets/images/logo.png' class="img-fluid" alt="Placeholder image"></div>
            <div class="col-4"></div>
        </div>
        
        <div class="row justify-content-between font-weight-bold border menu">
            <ul class="nav">
                <li class="nav-item">  @Html.ActionLink("Bạn muốn mua sách từ SanSachCu.TK?", "Index", "Home", null, new { @class = "nav-link" })</li>
                <li class="nav-item">  @Html.ActionLink("Bạn muốn mua từ người bán khác?", "Index", "ShowBD", null, new { @class = "nav-link" }) </li>
                <li class="nav-item">  @Html.ActionLink("Bạn muốn rao bán sách?", "Index", "BanSach", null, new { @class = "nav-link" }) </li>
                <li class="nav-item">  @Html.ActionLink("Bài tập của chúng em!", "BaiTap", "Home", null, new { @class = "nav-link" }) </li>


            </ul>

        </div>
        
        <div class="row">
            <div class="col-3">
                <div class="panel panel-info">
                    <div class="panel-heading">Danh Mục</div>
                    <div class="list-group">
                        @Html.ActionLink("Sách Văn Học ", "Vanhoc", "Home", null, new { @class = "list-group-item" })
                        @Html.ActionLink("Sách Hồi Kí", "HoiKi", "Home", null, new { @class = "list-group-item" })
                        @Html.ActionLink("Sách Kinh Tế", "KinhTe", "Home", null, new { @class = "list-group-item" })
                        @Html.ActionLink("Sách Văn Học Nước Ngoài", "VanHocNuocNgoai", "Home", null, new { @class = "list-group-item" })
                        @Html.ActionLink("Sách Học Tiểu Thuyết Lãng Mạn", "TieuThuyet", "Home", null, new { @class = "list-group-item" })
                        @Html.ActionLink("Sách Tham Khảo", "ThamKhao", "Home", null, new { @class = "list-group-item" })
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel-heading">Lịch sữ giao dịch</div>
                    <div class="panel-body">
                        <!--{Html.RenderAction("HistoryTransaction", "Home");}-->
                        @Html.Action("HistoryTransaction", "Home")

                    </div>
                </div>
            </div>

            <div class="col-6">
                
                @RenderBody()

            </div>


            <div class="col-3">
                <div class="panel panel-info">

                    <div class="panel-heading">Tìm Kiếm</div>
                    <div class="panel-body">
                        <fieldset style="border:thin;color:#999;">
                            @using (Html.BeginForm("KQTimKiem", "Home", FormMethod.Get, new { @class = "navbar-form navbar-right", role = "search", id = "search-form" }))
                {
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Tìm kiếm sách" name="SearchTerm" value="@ViewBag.SearchTerm" id="search-box">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default hidden-xs"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
    }
                        </fieldset>


                    </div>


                </div>
                <div id="lienhe">
                    <div id="slider">
                        <script>
                            var i = 0;
                            var images = [];
                            var time = 1000;

                            // Image list
                            images[0] = 'lienhe1.png';
                            images[1] = 'lienhe1.png';
                            images[2] = 'lienhe1.png';
                            images[3] = 'lienhe1.png';

                            // Change image
                            function changeImage() {

                                document.slide.src = '/Assets/images/' + images[i];

                                if (i < images.length - 1) {
                                    i++;
                                } else {
                                    i = 0;
                                }
                                setTimeout("changeImage()", time);
                            }

                            window.onload = changeImage;
                        </script>

                        <a href="http://m.me/thn.hoang.nhan" target="_blank"><img name="slide" width="170" height="170"></a>

                    </div>
                </div>
            </div>
            
            <div class="row">
                
                <div class="col-lg-12" align="center">
                    <hr />
                    <hr />
                    <a>Trải nghiệm cùng Sansachcu.tk</a><br>
                    Với mong muốn mang lại cho bạn đọc một điểm đến lý tưởng để mua sách với những trải nghiệm tốt nhất, Sansachcu.tk chỉ tập trung vào sản phẩm sách với hàng chục ngàn đầu sách khác nhau. Bạn có thể dễ dàng và nhanh chóng tìm được những đầu sách như ý với ít thao tác nhất và ít thời gian nhất.
                    Đội ngũ tư vấn của Sansachcu.tk với sự tận tâm và nhiệt tình luôn nỗ lực để sẵn sàng phục vụ các yêu cầu của bạn, và giúp bạn tìm ra những cuốn sách phù hợp nhất với nhu cầu đọc của mình.<br>

                    Sansachcu cảm ơn tất cả bạn đọc đã luôn ủng hộ và cam kết luôn phục vụ bạn hết mình!

                </div>



            </div>
        </div>
</body>
</html>